language: ruby
#env:
#- DB=sqlite3
#- DB=postgres
#before_script:
#- RAILS_ENV=production bundle exec rake db:migrate --trace
#- RAILS_ENV=production bundle exec rake db:migrate --trace
#- bundle exec rake db:test:prepare
script:
- bundle exec rspec spec/
services:
- postgresql
#bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: UVcGvYO5KJTfxGv3bBvrB4d5GRRa9jwjx3aWXkNwegxYcfjdnL5Vm66Af15S+YX6n4OEsEHNZM6H0jyWdILJ/Ld19mwZMtftY+dafeukDJxm7r9WLC39d3WL+NY/7VNgywXn+c2Dej7mQMXx0vdCjEhqZNwIcCVzlKAz8P96gjXeWgAONFU4Gt+b+UjdiDPw7cQe29w7+XhE4obwgTGlV9HcmT4pWtvUHABFV8xa+WTWNmPyNUqAY1d29iELT0FuSulTQ4bCW8IfdoY9XOSDvt84DYps3YUUJGxwNjyWOE8Nqz+WS2HO8/eTbY/EQubvNPMvmUFkUNC36q4SvlzNfySk2MgQ9Vhe6hGJxTi1AJENQC05s3r2ZMwFE8gAKU/Y344jMyjZUxCPWePBgReU7Q1c/KOVhWVd+uh3GKk+sUQ8322ZYQsW+q9mq8+updh0ku/su/CTE1TkroGqJgEojTuxBRbRqPaEEozPsOIF7jDvuzCCj8aIKxwG1Bqto6jKy2BNzo/dlu+Ck8AlWH0QJgs2xSz2IyHYV5cMjuBfD0CG5N7YS4DXFRJCh22PACTTEWt0xpWBCqzDSdmZ16+Qo+oh2rUdua1FLRZqygpPSbjHCnWcpQtWnZ8ofz5iNgm/KtQ4UX8DCVBzDimqgObBiHYGzBsdjQc3MP7+ajd8vXc=
    app_name: devanshu-sample
    on:
      repo: devanshu-m/devanshu-test
