language: ruby
#env:
#- DB=sqlite3
#- DB=postgres
#before_script:
#- RAILS_ENV=production bundle exec rake db:migrate --trace
#- RAILS_ENV=production bundle exec rake db:migrate --trace
#- bundle exec rake db:test:prepare
script:
- bundle exec rspec spec/
services:
- postgresql
#bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: fVkAc7D+UFGQK+CJXVezYOyXzZqrmbQwKFMqA2V+U1sdiJjCJi9vTW71aIOSQXJvm5sV/pOS82Ot2PmDrv/BnLFlYZvHVqFCxNlzSftU/g408eGlShzZWPM+tIK8ST7blbLF1b+EgkH5sfM1tvl/96B3urzUyFyIuoN/TpDAO1PRxAv8MV7pP++htOu8ZYVaTq5Zz84u8YH6g0vTawrgSD+tlqfAIYqcRvzIuvbLbA2xU3Zvrk4ZfO3FHOu3yA28Rt+X6X2piEckeZTC5BnicoEVWg0b6ZMgRwUQLi0EyyZ/cJdDZ5VaRV2lCgJLeceM+zSlW+3AK40AtnMHKYtos39TG5/ukccsLqzysuEJLE02TCf8NiHNOl8XBlOhG/rBLtg0EX/8XA+ca8ljgfRHNN4yDaADcBMuIG8sGiDab04eP884qParwF4j7Kww7Nj+l5BnOkKPS5tlarfVijeqwIBK/Wwm23QJw85GATULdHI72vXrK1uwmABcupItsT/pkNmNV2PcICJuneBnRy/DM2Bl1dowtwCCAqpEFicHWTUUeJio/tVt0yeSnJdWbcb26C53HTFx2WrN+sCxzwAnApM7QhWXhzjDxkweT+fzbsV6F7a8bgjFBLoFmlnsg2m0Xf3jDy8rF9oJoorGyShH4Pm7ZUOEXuYi7r1yJR9MM2E=
  app: devanshu-sample
  on:
    repo: devanshu-m/devanshu-test
